// Local test harness; not a Supabase deployment script.
import { PGlite } from '@electric-sql/pglite';
import { readFile } from 'node:fs/promises';
const db=new PGlite();
await db.exec(`
  create role anon; create role authenticated; create role service_role bypassrls;
  create schema auth; create schema storage;
  create table auth.users(id uuid primary key, email_confirmed_at timestamptz);
  create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
  grant usage on schema auth,storage,public to anon,authenticated,service_role;
  grant execute on function auth.uid() to authenticated,anon,service_role;
  create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
  create table storage.objects(name text primary key,bucket_id text);
  alter table storage.objects enable row level security;
  grant select,insert,delete,update on storage.objects to anon,authenticated;
  create function storage.foldername(text) returns text[] language sql immutable as $$ select (string_to_array($1,'/'))[1:array_length(string_to_array($1,'/'),1)-1] $$;
`);
await db.exec(await readFile(new URL('../supabase/migrations/202610060001_rooms.sql',import.meta.url),'utf8'));
const u='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222',id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',id2='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
await db.query('insert into auth.users values($1,now()),($2,now())',[u,other]);
const reserve=async(roomId,limit=2)=>db.query("select public.reserve_room($1,$2,'Room','Living room','Modern vintage','Warm room','pk',$3,$4) as result",[roomId,u,`${u}/${roomId}/source.jpg`,limit]);
const check=(v,m)=>{if(!v)throw Error(m);console.log('PASS',m);};
const rejected=async(fn,m)=>{let failed=false;try{await fn();}catch{failed=true;}check(failed,m);};
check((await reserve(id)).rows[0].result.created,'First job is reserved');
check(!(await reserve(id)).rows[0].result.created,'Repeated submission is idempotent');
await rejected(()=>reserve(id2),'Concurrent active room is rejected');
await db.query("update public.rooms set status='ready' where id=$1",[id]);await reserve(id2);
await db.query("update public.rooms set status='ready' where id=$1",[id2]);
await rejected(()=>reserve('cccccccc-cccc-4ccc-8ccc-cccccccccccc'),'Daily generation limit is enforced');
await db.exec(`set role authenticated; set request.jwt.claim.sub='${other}';`);
check((await db.query('select * from public.rooms')).rows.length===0,'Other user cannot read room');
await rejected(()=>db.query('insert into public.favourites values($1,$2)',[other,id]),'Other user cannot favourite room');
await rejected(()=>db.query("select public.use_credit($1,'design',999)",[other]),'Client cannot invoke privileged quota function');
await rejected(()=>db.query("insert into storage.objects values($1,'rooms')",[`${u}/${id}/source.jpg`]),'Other user cannot upload into owner folder');
await db.exec(`set request.jwt.claim.sub='${u}';`);
check((await db.query('select * from public.rooms')).rows.length===2,'Owner sees their rooms');
await db.query("insert into storage.objects values($1,'rooms')",[`${u}/${id}/source.jpg`]);
check((await db.query('select * from storage.objects')).rows.length===1,'Owner can upload their original');
await rejected(()=>db.query("insert into storage.objects values($1,'rooms')",[`${u}/${id}/result.png`]),'Client cannot forge generated result');
await db.exec('reset role;');await db.query('select public.lock_account_delete($1)',[u]);
await rejected(()=>reserve('cccccccc-cccc-4ccc-8ccc-cccccccccccc',10),'Account deletion blocks new generations');
await db.exec(`set role authenticated; set request.jwt.claim.sub='${u}';`);
await rejected(()=>db.query("insert into storage.objects values($1,'rooms')",[`${u}/${id2}/source.jpg`]),'Account deletion blocks new uploads');
await db.close();
